# note: uncomment ui secion below for mongo-express
# ref: https://hub.docker.com/_/mongo

version: '3'

networks:
  default:
    name: cosmos-scraper

services:
  db:
    container_name: cosmos-scraper-db
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - ${CS_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${CS_DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${CS_DB_PASS}"
  # ui:
  #   container_name: cosmos-scraper-ui
  #   image: mongo-express
  #   restart: unless-stopped
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "${CS_DB_USER}"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "${CS_DB_PASS}"
  #     ME_CONFIG_MONGODB_URL: "mongodb://${CS_DB_USER}:${CS_DB_PASS}@db:${CS_DB_PORT}/"
